[envs.changelog]
dependencies = ["scriv"]
detached = true
installer = "uv"
scripts = {add = "scriv create --add", collect = ["scriv collect --add", "- pre-commit run --files=CHANGELOG.md > /dev/null"]}

[envs.default]
dependencies = [
  "pre-commit",
  "dash[dev]>=3.0.0"  # provides dash-generate-components, required by `npm run build`
]
installer = "uv"

[envs.default.scripts]
example = "python usage.py"
lint = ["hatch run npm:lint", "pre-commit run {args} --all-files"]
pip = '"{env:HATCH_UV}" pip {args}'
prep-release = [
  "hatch version release",
  "hatch run changelog:collect",
  "hatch run changelog:add",
  'echo "Now raise a PR to merge into main with title: [Release] Release of vizro-dash-components $(hatch version)"'
]
npm-build = "npm run build"
npm-fmt = "npm run fmt:js"
npm-install = "npm install --legacy-peer-deps"
npm-lint = "npm run lint:js"
