[build.targets.wheel]
packages = ["src/vizro_chat_component"]

[envs.all]

[[envs.all.matrix]]
python = ["3.9", "3.10", "3.11", "3.12"]

[envs.default]
dependencies = [
  "devtools[pygments]",
  "coverage[toml]>=6.5",
  "pytest",
  "pytest-mock",
  "chromedriver-autoinstaller-fix",
  "toml",
  "dash[testing]",
  "openai"
]

[envs.default.scripts]
example = "cd examples; python app.py"
lint = "hatch run lint:lint {args:--all-files}"

[envs.lint]
dependencies = [
  "pre-commit"
]
detached = true
scripts = {lint = "SKIP=gitleaks pre-commit run {args:--all-files}"}

[publish.index]
disable = true
