"""File to store constants."""

ALL_OPTION = "ALL"
NONE_OPTION = "NONE"
STATIC_URL_PREFIX = "vizro"
MODULE_PAGE_404 = "not_found_404"
EMPTY_SPACE_CONST = -1
UPDATE_FIGURES_ACTION_PREFIX = "update_figures_action"
FILTER_ACTION_PREFIX = "filter_action"
PARAMETER_ACTION_PREFIX = "parameter_action"
ACCORDION_DEFAULT_TITLE = "SELECT PAGE"
