name: 🐛 Bug report
description: Something is not working correctly
labels: "Needs triage :mag:, Bug Report :bug:"

body:
  - type: markdown
    attributes:
      value: >-
        Hi there! Thank you so much for taking the time to fill in this bug report.

  - type: checkboxes
    attributes:
      label: Have you already looked into this bug?
      description: Since our triage resources are limited, we’d really appreciate it if you could take a moment to check whether this bug has already been reported or documented.
      options:
        - label: I've reviewed the [release notes](https://github.com/mckinsey/vizro/releases) for relevant migration steps
        - label: I've searched through [existing issues](https://github.com/mckinsey/vizro/issues) for similar reports
        - label: I've already searched online (e.g. Dash documentation) but couldn't find anything relevant

  - type: dropdown
    attributes:
      label: Which package?
      options:
        - vizro
        - vizro-ai
    validations:
      required: true

  - type: input
    attributes:
      label: Package version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce
      description: Provide steps to reproduce this bug. You can also [use a PyCafe link](https://py.cafe/snippet/vizro/v1) to share your example.
      placeholder: |
        1. Get package from '...'
        2. Then run '...'
        3. An error occurs.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Output
      description: >-
        If you can, provide the output of the steps above, including the commands
        themselves and Vizro's output/traceback etc.  If possible,
        provide a screenshot highlighting the issue or [link to a PyCafe example](https://py.cafe/snippet/vizro/v1).

        If you want to present output from multiple commands, prefix
        the line containing the command with `$ `. Ensure that
        the "How to reproduce" section contains matching instructions.

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).
          required: true
