name: Bug report
description: Something is not working correctly
labels: "Status: Needs triage :mag:, Issue: Bug Report :bug:"

body:
  - type: markdown
    attributes:
      value: >-
        Hi there! Thank you so much for taking the time to fill in this bug form. It will be
        a valuable contribution to Vizro.

        We'd appreciate it if you could search on Vizro's existing issues prior to filing
        a bug report to avoid any duplicate tickets, as we have limited maintainer capacity to triage
        them. Thanks!

  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.

  - type: input
    attributes:
      label: vizro version
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
    validations:
      required: true
  - type: input
    attributes:
      label: OS
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce
      description: Please provide steps to reproduce this bug.
      placeholder: |
        1. Get package from '...'
        2. Then run '...'
        3. An error occurs.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Output
      description: >-
        Provide the output of the steps above, including the commands
        themselves and Vizro's output/traceback etc.  If possible,
        please also provide a screenshot highlighting the issue.

        If you want to present output from multiple commands, please prefix
        the line containing the command with `$ `. Please also ensure that
        the "How to reproduce" section contains matching instructions for
        reproducing this.

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).
          required: true
