name: 🌟 Feature request
description: Suggest an idea for this project
labels: "Needs triage :mag:, Feature Request :nerd_face:"

body:
  - type: markdown
    attributes:
      value: >-
        Hi there! Thank you so much for taking the time to fill in this feature request.

  - type: checkboxes
    attributes:
      label: Have you already looked into this request?
      description: Since our triage resources are limited, we’d really appreciate it if you could take a moment to check whether this feature has already been suggested or documented.
      options:
        - label: I've reviewed the [Vizro documentation](https://vizro.readthedocs.io/en/stable) to see if this feature is already supported, including through [Vizro extensions](https://vizro.readthedocs.io/en/stable/pages/user-guides/extensions/)
        - label: I've searched through [existing issues](https://github.com/mckinsey/vizro/issues) for similar requests
        - label: I've already searched online (e.g. Dash documentation) but couldn't find anything relevant

  - type: dropdown
    attributes:
      label: Which package?
      options:
        - vizro
        - vizro-mcp
        - vizro-ai
        - vizro-e2e-flow
  - type: textarea
    attributes:
      label: What's the problem this feature will solve?
      description: >-
        What are you trying to do, that you are unable to achieve with Vizro as it
        currently stands? Have you tried to work around the problem using Vizro or other tools?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >-
        Clear and concise description of what you want to happen. Please use examples
        of real world use cases that this would help with, and how it solves the
        problem described above.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).
          required: true
