name: Feature request
description: Suggest an idea for this project
labels: "Needs triage :mag:, Feature Request :nerd_face:"

body:
  - type: markdown
    attributes:
      value: >-
        Hi there! Thank you so much for taking the time to fill in this feature request.
        As we have limited triage capacity, we'd appreciate it if you could search on Vizro's
        existing issues prior to submission to avoid any duplicates. Thanks!
  - type: dropdown
    attributes:
      label: Which package?
      options:
        - vizro
        - vizro-ai
  - type: textarea
    attributes:
      label: What's the problem this feature will solve?
      description: >-
        What are you trying to do, that you are unable to achieve with Vizro as it
        currently stands? Have you tried to work around the problem using Vizro or other tools?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >-
        Clear and concise description of what you want to happen. Please use examples
        of real world use cases that this would help with, and how it solves the
        problem described above.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).
          required: true
