name: ❔ How to do ...?
description: General questions around Vizro
labels: "Needs triage :mag:, General Question :question:"

body:
  - type: markdown
    attributes:
      value: >-
        Hi there! Thank you so much for taking the time to fill in this general question.

  - type: checkboxes
    attributes:
      label: Have you already looked into this topic?
      description: Since our triage capacity is limited, we’d really appreciate it if you could take a moment to check whether your question has already been answered or documented.
      options:
        - label: I've reviewed the [Vizro documentation](https://vizro.readthedocs.io/en/stable) for any relevant information
        - label: I've searched through [existing issues](https://github.com/mckinsey/vizro/issues) for similar questions
        - label: I've already searched online (e.g., Dash documentation) but couldn’t find anything helpful

  - type: textarea
    attributes:
      label: Question
      description: >-
        Please post your question here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code/Examples
      description: >-
        Post any supporting code around your question here or as a [PyCafe link](https://py.cafe/snippet/vizro/v1).
        Don't forget to include the package version, if it's relevant.

  - type: dropdown
    attributes:
      label: Which package?
      options:
        - vizro
        - vizro-mcp
        - vizro-ai

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).
          required: true
