name: General question
description: General questions around Vizro
labels: "Issue: Needs triage :mag:, Issue: General Question :question:"

body:
  - type: markdown
    attributes:
      value: >-
        Hi there! Thank you so much for taking the time to fill in this general question.
        As we have limited triage capacity, we'd appreciate it if you could search on Vizro's
        existing issues prior to submission to avoid any duplicates. Thanks!

  - type: textarea
    attributes:
      label: Question
      description: >-
        Please post your question here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code/Examples
      description: >-
        Post any supporting code around your question here or as a [py.cafe link](https://py.cafe/snippet/vizro/v1).
        Don't forget to include the package version, if it's relevant.

  - type: dropdown
    attributes:
      label: Which package?
      options:
        - vizro
        - vizro-ai

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).
          required: true
