name: "Create artifacts and slack notifications"
description: "Creates failed artifacts with screenshots and sends slack notifications if build failed"

runs:
  using: "composite"
  steps:
    - name: Copy failed screenshots
      shell: bash
      run: |
        mkdir ${{ env.PROJECT_PATH }}failed_screenshots
        cd ${{ env.PROJECT_PATH }}
        cp -r /tmp/dash_artifacts failed_screenshots
        cp *.png failed_screenshots || true

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Failed screenshots
        path: |
          ${{ env.PROJECT_PATH }}failed_screenshots

    - name: Send custom JSON data to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "text": "${{ env.TESTS_NAME }} build result: ${{ job.status }}\nBranch: ${{ github.head_ref }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
