name: "Create artifacts and slack notifications"
description: "Creates failed artifacts with screenshots and sends slack notifications if build failed"

runs:
  using: "composite"
  steps:
    - name: Copy failed screenshots
      shell: bash
      run: |
        mkdir ${{ env.PROJECT_PATH }}failed_screenshots
        cd ${{ env.PROJECT_PATH }}
        cp -r /tmp/dash_artifacts failed_screenshots
        cp *.png failed_screenshots || true

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Failed screenshots ${{ env.FAILED_SCREENSHOTS_ARCHIVE_POSTFIX }}
        path: |
          ${{ env.PROJECT_PATH }}failed_screenshots

    - name: Send custom JSON data to Slack
      id: slack
      # used pinned commit hash for security reasons
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        payload: |
          {
            "text": "${{ env.TESTS_NAME }} build result: ${{ job.status }}\nBranch: ${{ github.head_ref }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
        webhook: ${{ env.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
