name: CircleCI tests trigger

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  circleci-trigger:
    name: CircleCI tests trigger
    environment: circleci_secrets
    runs-on: ubuntu-latest
    steps:
      - name: Ping CircleCI pipeline
        run: |
          CREATED_PIPELINE=$(curl --request POST \
            --url "${{ secrets.QA_PIPELINE_URL }}" \
            --header "Circle-Token: ${{ secrets.CIRCLECI_API_KEY }}" \
            --header "content-type: application/json" \
            --data '{"branch":"${{ github.head_ref }}", "parameters":{"branch":"${{ github.head_ref }}", "vizro_branch": "${{ github.head_ref }}", "tag": "${{  github.ref_name }}"}}' \
          | jq -r '.id'
          )
          if [[ "$CREATED_PIPELINE" == "null" ]]; then
            CREATED_PIPELINE=$(curl --request POST \
            --url "${{ secrets.QA_PIPELINE_URL }}" \
            --header "Circle-Token: ${{ secrets.CIRCLECI_API_KEY }}" \
            --header "content-type: application/json" \
            --data '{"branch":"main", "parameters":{"branch":"main", "vizro_branch": "${{ github.head_ref }}", "tag": "${{  github.ref_name }}"}}' \
            | jq -r '.id'
            )
          fi
          echo "my created pipeline"
          echo $CREATED_PIPELINE
          mkdir ~/workspace
          echo $CREATED_PIPELINE > pipeline.txt
