name: CircleCI tests trigger

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  circleci-trigger-fork:
    if: ${{ github.event.pull_request.head.repo.fork }}
    name: CircleCI tests trigger
    runs-on: ubuntu-latest
    steps:
      - name: Passed fork step
        run: echo "Success!"

  circleci-trigger:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    name: CircleCI tests trigger
    environment: circleci_secrets
    runs-on: ubuntu-latest
    steps:
      - name: Start CircleCI pipeline
        run: |
          create_circleci_pipeline() {
            local branch=$1
            local vizro_branch=$2
            local tag=$3

            local json_data=$(jq -n --arg branch "$branch" --arg vizro_branch "$vizro_branch" --arg tag "$tag" '{branch: $branch, parameters: {branch: $branch, vizro_branch: $vizro_branch, tag: $tag}}')

            curl --silent --request POST \
              --url "${{ secrets.QA_PIPELINE_URL }}" \
              --header "Circle-Token: ${{ secrets.CIRCLECI_API_KEY }}" \
              --header "content-type: application/json" \
              --data "$json_data" \
            | jq -r '.id'
          }

          CREATED_PIPELINE=$(create_circleci_pipeline "${{ github.head_ref }}" "${{ github.head_ref }}" "$github_tag")

          # If the above returns null then the QA repo doesn't contain current dev branch, so we use main branch.
          if [[ "$CREATED_PIPELINE" == "null" ]]; then
            CREATED_PIPELINE=$(create_circleci_pipeline "main" "${{ github.head_ref }}" "$github_tag")
          fi
          echo "Started pipeline with id $CREATED_PIPELINE"

          echo "CREATED_PIPELINE=$CREATED_PIPELINE" >> $GITHUB_ENV

      - name: Wait for pipeline to run
        run: sleep 60

      - name: Check pipeline status
        run: |
          get_pipeline_status() {
            curl --silent --request GET \
                 --url "https://circleci.com/api/v2/pipeline/$CREATED_PIPELINE/workflow" \
                 --header "Circle-Token: ${{ secrets.CIRCLECI_API_KEY }}" \
                 --header "content-type: application/json" \
              | jq -r '.items[0].status'
          }

          while pipeline_status=$(get_pipeline_status); [[ "$pipeline_status" == "running" ]]; do
            echo $pipeline_status
            sleep 15
          done

          if [[ "$created_pipeline_status" != "success" ]]; then
              echo "Pipeline not completed sucessfully - status was ${created_pipeline_status}"
              exit 1
          fi
