name: Docs Links Checker

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.12"

jobs:
  create-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Hatch
        run: pip install hatch

      - name: vizro-core link check
        working-directory: ./vizro-core
        run: |
          hatch run docs:pip tree
          hatch run docs:build
          hatch run docs:link-check

      - name: vizro-ai link check
        working-directory: ./vizro-ai
        if: always()
        run: |
          hatch run docs:pip tree
          hatch run docs:build
          hatch run docs:link-check
