name: Test release vizro-experimental to TestPyPI

permissions:
  contents: read

defaults:
  run:
    working-directory: vizro-experimental

on:
  push:
    branches:
      - ci/vizro-experimental-release
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"

jobs:
  build-publish-test:
    runs-on: ubuntu-latest
    environment: pypi-test
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Hatch
        run: pip install hatch

      - name: Build package
        run: hatch build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: vizro-experimental/dist
          repository-url: https://test.pypi.org/legacy/
