name: Unit tests for vizro_chat_component

defaults:
  run:
    working-directory: vizro-experimental

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches:

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  test-unit-vizro-chat-component:
    name: test-unit-vizro-chat-component on Py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.11"
            hatch-env: all.py3.11
          - python-version: "3.12"
            hatch-env: all.py3.12
          - python-version: "3.13"
            hatch-env: all.py3.13
          - python-version: "3.14"
            hatch-env: all.py3.14

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install hatch

      - name: Run unit tests
        run: hatch run test-unit
