name: Vizro qa notebooks tests trigger

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  vizro-qa-trigger-fork:
    if: ${{ github.event.pull_request.head.repo.fork }}
    name: Vizro qa notebooks tests trigger
    runs-on: ubuntu-latest
    steps:
      - name: Passed fork step
        run: echo "Success!"

  vizro-qa-trigger:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    name: Vizro qa notebooks tests trigger
    environment: vizro_secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tests trigger
        run: |
          export INPUT_OWNER=${{ secrets.ORG }}
          export INPUT_REPO=${{ secrets.QA_REPO }}
          export INPUT_WORKFLOW_FILE_NAME=${{ secrets.NOTEBOOKS_TEST_FILE }}
          export INPUT_GITHUB_TOKEN=${{ secrets.VIZRO_SVC_PAT }}
          export INPUT_REF=${{ github.head_ref }}
          tools/trigger-workflow-and-wait.sh
